In [1]:
#load the csv file using pandas.dosplay the first and last reords chek the missing value and duplicate record and generate basic desrespactivestaticsa
#use pandas operation such as filtering sorting goupby,,aggregate value,discount,customer segment,category,sup-category,region
#use numpy for numerical analysis such as mean median,profit,catego the sales values and creation of at least one useful derived numerical

**This is C2 cycle**

In [3]:
import pandas as pd
import numpy as np

super =df.read_csv("superstore_excel-selected-columns")

In [9]:
df=pd.read_csv("superstore_excel-selected-columns (1).csv")
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders
...,...,...,...,...,...,...,...,...,...,...
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [10]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders

In [11]:
df.tail()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [12]:
df.describe()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,5000,728,30,4,3853,4833,3,4,3,14
top,CA-198797,2023-10-15,2025-04-27,Second Class,CUST-4323,Michael Smith,Corporate,South,Furniture,Chairs
freq,1,17,198,1305,5,4,1686,1287,1670,447

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   str
 1   Order Date     5000 non-null   str
 2   Ship Date      5000 non-null   str
 3   Ship Mode      5000 non-null   str
 4   Customer ID    5000 non-null   str
 5   Customer Name  5000 non-null   str
 6   Segment        5000 non-null   str
 7   Region         5000 non-null   str
 8   Category       5000 non-null   str
 9   Sub-Category   5000 non-null   str
dtypes: str(10)
memory usage: 856.9 KB

In [14]:
df.isnull()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False

In [17]:
df.shape

(5000, 10)

In [19]:
df.size

50000

In [26]:
df.dtypes

Order ID         str
Order Date       str
Ship Date        str
Ship Mode        str
Customer ID      str
Customer Name    str
Segment          str
Region           str
Category         str
Sub-Category     str
dtype: object

In [31]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Region', 'Category', 'Sub-Category'],
      dtype='str')

In [35]:
a = df[df['Category'] == 'Technology']
a

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
20,CA-431867,2023-09-02,2025-05-07,First Class,CUST-3050,Katherine Rodriguez,Corporate,Central,Technology,Copiers
22,CA-129071,2024-06-15,2025-04-23,Same Day,CUST-9684,Ashley James DDS,Home Office,East,Technology,Accessories
24,CA-758620,2024-07-10,2025-04-25,Standard Class,CUST-7646,Ashley Wilkerson,Consumer,Central,Technology,Accessories
28,CA-930209,2024-11-13,2025-04-15,Same Day,CUST-2863,Mr. Brad Price,Corporate,East,Technology,Copiers
...,...,...,...,...,...,...,...,...,...,...
4990,CA-900960,2025-02-04,2025-05-05,Second Class,CUST-6952,Trevor Mills,Home Office,West,Technology,Accessories
4991,CA-544225,2023-06-20,2025-05-03,First Class,CUST-1952,April Wright,Consumer,Central,Technology,Machines
4993,CA-743555,2023-11-11,2025-04-26,Second Class,CUST-3878,Mary Ramirez,Consumer,West,Technology,Copiers
4994,CA-450931,2024-12-23,2025-04-25,Second Class,CUST-5025,Lisa Moore,Corporate,South,Technology,Accessories
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories

In [37]:
#Sorted data
sorted_data =df.sort_values(by = "Segment",ascending = False)
sorted_data

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
5,CA-990541,2023-09-20,2025-04-17,Same Day,CUST-6746,Gabriel Donaldson,Home Office,East,Office Supplies,Storage
7,CA-701472,2023-08-12,2025-04-23,First Class,CUST-4421,Grant Garcia,Home Office,East,Office Supplies,Storage
8,CA-670780,2024-12-11,2025-04-28,Second Class,CUST-8240,Mr. Robert Le Jr.,Home Office,South,Office Supplies,Storage
...,...,...,...,...,...,...,...,...,...,...
4983,CA-854904,2023-10-21,2025-04-28,First Class,CUST-1384,Robert Shaw,Consumer,East,Technology,Computers
4984,CA-409355,2023-08-29,2025-04-10,First Class,CUST-6641,Jennifer Jones,Consumer,South,Furniture,Furnishings
4986,CA-349318,2024-12-25,2025-04-18,First Class,CUST-1712,Mark Lynch,Consumer,Central,Technology,Copiers
4991,CA-544225,2023-06-20,2025-05-03,First Class,CUST-1952,April Wright,Consumer,Central,Technology,Machines
4993,CA-743555,2023-11-11,2025-04-26,Second Class,CUST-3878,Mary Ramirez,Consumer,West,Technology,Copiers

d=df.groupby("Category")
print(d)

In [38]:
#Groupby
d=df.groupby("Category")
print(d)

<pandas.api.typing.DataFrameGroupBy object at 0x00000294737F2900>