In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("superstore_excel-selected-columns (1).csv")
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders
...,...,...,...,...,...,...,...,...,...,...
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [7]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders

In [8]:
df.tail()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [11]:
df.dtypes

Order ID         str
Order Date       str
Ship Date        str
Ship Mode        str
Customer ID      str
Customer Name    str
Segment          str
Region           str
Category         str
Sub-Category     str
dtype: object

In [13]:
df.describe

<bound method NDFrame.describe of        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0     CA-198797  2024-10-06  2025-05-01    Second Class   CUST-4170
1     CA-233440  2023-06-12  2025-05-05     First Class   CUST-1196
2     CA-691533  2024-04-18  2025-04-24  Standard Class   CUST-2985
3     CA-277218  2023-11-02  2025-05-07     First Class   CUST-2412
4     CA-311967  2023-07-15  2025-04-14     First Class   CUST-3728
...         ...         ...         ...             ...         ...
4995  CA-780853  2025-03-04  2025-04-13    Second Class   CUST-8307
4996  CA-489090  2023-06-20  2025-04-28        Same Day   CUST-1311
4997  CA-203624  2024-03-11  2025-04-23  Standard Class   CUST-6014
4998  CA-562734  2024-11-04  2025-04-20        Same Day   CUST-1274
4999  CA-852804  2024-03-22  2025-04-24     First Class   CUST-6238

       Customer Name      Segment   Region         Category Sub-Category
0      Ruben Ramirez  Home Office    South       Technology      Copiers
1       Jesse Ortega  Home Office  Central        Furniture  Furnishings
2     Kathryn Castro    Corporate     East        Furniture       Chairs
3      Sharon Taylor     Consumer    South  Office Supplies       Labels
4      David Murillo    Corporate    South  Office Supplies      Binders
...              ...          ...      ...              ...          ...
4995      Adam Scott  Home Office     West  Office Supplies          Art
4996  Kathryn Miller  Home Office    South        Furniture       Chairs
4997  Tiffany Moreno    Corporate     East       Technology  Accessories
4998  Yolanda Conner    Corporate     West        Furniture       Chairs
4999   Michael Giles  Home Office     East        Furniture       Chairs

[5000 rows x 10 columns]>

In [16]:
df.shape[1]

10

df.columns()

In [18]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Region', 'Category', 'Sub-Category'],
      dtype='str')

In [20]:
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Region           0
Category         0
Sub-Category     0
dtype: int64

In [21]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [24]:
df["Ship Mode"].value_counts()

Ship Mode
Second Class      1305
Same Day          1245
Standard Class    1234
First Class       1216
Name: count, dtype: int64

In [26]:
df["Segment"].value_counts()

Segment
Corporate      1686
Home Office    1683
Consumer       1631
Name: count, dtype: int64

In [27]:
df["Sub-Category"].value_counts().head(10)

Sub-Category
Chairs         447
Tables         418
Furnishings    409
Bookcases      396
Copiers        361
Binders        358
Labels         355
Accessories    345
Phones         339
Paper          334
Name: count, dtype: int64

#TASK2

In [43]:
df["Order Date"] = pd.to_datetime(df["Order Date"], errors="coerce")
Order_years = df["Order Date"].dt.year.dropna().to_numpy()
Order_years
print(np.mean(Order_years))
print(np.min(Order_years))
np.max(Order_years)
np.min(Order_years)

2023.7718
2023

np.int32(2023)

In [50]:
df["Order Date"] = pd.to_datetime(df["Order Date"], errors="coerce")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], errors="coerce")
df["Order year"] = df["Order Date"].dt.year
df["Order month"] = df["Order Date"].dt.month
df["Shipping days"]= (df["Ship Date"]-df["Order Date"]).dt.days
display(df[["Order Date","Order month","Ship Date","Shipping days","Order year"]].head() )

  Order Date  Order month  Ship Date  Shipping days  Order year
0 2024-10-06           10 2025-05-01            207        2024
1 2023-06-12            6 2025-05-05            693        2023
2 2024-04-18            4 2025-04-24            371        2024
3 2023-11-02           11 2025-05-07            552        2023
4 2023-07-15            7 2025-04-14            639        2023